"""Unified API error codes — aligned with docs/api-specification.md §7."""

from __future__ import annotations

from enum import Enum
from typing import Any


class ApiErrorCode(str, Enum):
    # Generic
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

    # Auth
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_INVALID_SIGNATURE = "AUTH_INVALID_SIGNATURE"
    AUTH_INVALID_NONCE = "AUTH_INVALID_NONCE"
    AUTH_INVALID_ID_TOKEN = "AUTH_INVALID_ID_TOKEN"
    AUTH_PROVIDER_NOT_SUPPORTED = "AUTH_PROVIDER_NOT_SUPPORTED"
    AUTH_MISSING_PARAMS = "AUTH_MISSING_PARAMS"
    AUTH_REFRESH_EXPIRED = "AUTH_REFRESH_EXPIRED"
    AUTH_REFRESH_INVALID = "AUTH_REFRESH_INVALID"
    AUTH_REFRESH_REVOKED = "AUTH_REFRESH_REVOKED"
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    SURVEY_ALREADY_SUBMITTED = "SURVEY_ALREADY_SUBMITTED"
    SURVEY_INVALID_FIELD = "SURVEY_INVALID_FIELD"

    # Panda
    PANDA_NOT_FOUND = "PANDA_NOT_FOUND"
    PANDA_NOT_OWNER = "PANDA_NOT_OWNER"
    PANDA_MINT_DISABLED = "PANDA_MINT_DISABLED"
    PANDA_MAX_SUPPLY = "PANDA_MAX_SUPPLY"
    PANDA_MINT_RATE_LIMIT = "PANDA_MINT_RATE_LIMIT"
    PANDA_TX_FAILED = "PANDA_TX_FAILED"
    PANDA_NAME_INVALID = "PANDA_NAME_INVALID"
    PANDA_NAME_PROFANITY = "PANDA_NAME_PROFANITY"
    PANDA_IS_TRADING = "PANDA_IS_TRADING"

    # Strategy
    STRATEGY_TEXT_TOO_SHORT = "STRATEGY_TEXT_TOO_SHORT"
    STRATEGY_TEXT_TOO_LONG = "STRATEGY_TEXT_TOO_LONG"
    STRATEGY_BODY_EMPTY = "STRATEGY_BODY_EMPTY"
    STRATEGY_NO_VALID_RULES = "STRATEGY_NO_VALID_RULES"
    STRATEGY_RULE_INVALID = "STRATEGY_RULE_INVALID"
    STRATEGY_PARSE_FAILED = "STRATEGY_PARSE_FAILED"
    STRATEGY_RATE_LIMIT = "STRATEGY_RATE_LIMIT"
    STRATEGY_NOT_FOUND = "STRATEGY_NOT_FOUND"
    STRATEGY_POLICY_CONFLICT = "STRATEGY_POLICY_CONFLICT"

    # Simulation
    SIM_ALREADY_RUNNING = "SIM_ALREADY_RUNNING"
    SIM_NO_STRATEGY = "SIM_NO_STRATEGY"
    SIM_INVALID_SPEED = "SIM_INVALID_SPEED"
    SIM_NOT_RUNNING = "SIM_NOT_RUNNING"

    # v3.1 Agent Wallet / Trading Policy
    VAULT_NOT_FOUND = "VAULT_NOT_FOUND"
    VAULT_NOT_ACTIVE = "VAULT_NOT_ACTIVE"
    VAULT_OWNER_MISMATCH = "VAULT_OWNER_MISMATCH"
    VAULT_SYNC_PENDING = "VAULT_SYNC_PENDING"
    POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
    POLICY_PAUSED = "POLICY_PAUSED"
    POLICY_PAIR_NOT_ALLOWED = "POLICY_PAIR_NOT_ALLOWED"
    POLICY_NOTIONAL_EXCEEDED = "POLICY_NOTIONAL_EXCEEDED"
    POLICY_DAILY_LOSS_EXCEEDED = "POLICY_DAILY_LOSS_EXCEEDED"
    POLICY_VERSION_STALE = "POLICY_VERSION_STALE"
    POLICY_AGENT_REVOKED = "POLICY_AGENT_REVOKED"
    POLICY_MIRROR_STALE = "POLICY_MIRROR_STALE"
    LEDGER_ACCOUNT_NOT_FOUND = "LEDGER_ACCOUNT_NOT_FOUND"
    LEDGER_INSUFFICIENT_BALANCE = "LEDGER_INSUFFICIENT_BALANCE"
    LEDGER_POSITION_NOT_FOUND = "LEDGER_POSITION_NOT_FOUND"
    LEDGER_TRANSACTION_FAILED = "LEDGER_TRANSACTION_FAILED"
    TRADE_FACT_NOT_FOUND = "TRADE_FACT_NOT_FOUND"
    TRADE_FACT_ALREADY_REVIEWED = "TRADE_FACT_ALREADY_REVIEWED"
    TRADE_FACT_PROOF_NOT_ELIGIBLE = "TRADE_FACT_PROOF_NOT_ELIGIBLE"
    CHAIN_PROOF_DISABLED = "CHAIN_PROOF_DISABLED"
    CHAIN_PROOF_DUPLICATE = "CHAIN_PROOF_DUPLICATE"
    CHAIN_PROOF_RATE_LIMITED = "CHAIN_PROOF_RATE_LIMITED"
    CHAIN_PROOF_TX_FAILED = "CHAIN_PROOF_TX_FAILED"
    AGENT_SIGNER_NOT_CONFIGURED = "AGENT_SIGNER_NOT_CONFIGURED"
    AGENT_SIGNER_UNAUTHORIZED = "AGENT_SIGNER_UNAUTHORIZED"
    AGENT_SIGNER_NETWORK_NOT_ALLOWED = "AGENT_SIGNER_NETWORK_NOT_ALLOWED"

    # Review / Skill Memory
    REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND"
    REVIEW_NOT_READY = "REVIEW_NOT_READY"
    REVIEW_EVIDENCE_MISSING = "REVIEW_EVIDENCE_MISSING"
    SKILL_VERSION_NOT_FOUND = "SKILL_VERSION_NOT_FOUND"


HTTP_STATUS_BY_CODE: dict[ApiErrorCode, int] = {
    ApiErrorCode.INTERNAL_ERROR: 500,
    ApiErrorCode.VALIDATION_ERROR: 400,
    ApiErrorCode.NOT_FOUND: 404,
    ApiErrorCode.RATE_LIMIT_EXCEEDED: 429,
    ApiErrorCode.SERVICE_UNAVAILABLE: 503,
    ApiErrorCode.AUTH_UNAUTHORIZED: 401,
    ApiErrorCode.AUTH_TOKEN_EXPIRED: 401,
    ApiErrorCode.AUTH_INVALID_SIGNATURE: 401,
    ApiErrorCode.AUTH_INVALID_NONCE: 401,
    ApiErrorCode.AUTH_INVALID_ID_TOKEN: 401,
    ApiErrorCode.AUTH_PROVIDER_NOT_SUPPORTED: 400,
    ApiErrorCode.AUTH_MISSING_PARAMS: 400,
    ApiErrorCode.AUTH_REFRESH_EXPIRED: 401,
    ApiErrorCode.AUTH_REFRESH_INVALID: 401,
    ApiErrorCode.AUTH_REFRESH_REVOKED: 401,
    ApiErrorCode.AUTH_USER_NOT_FOUND: 404,
    ApiErrorCode.SURVEY_ALREADY_SUBMITTED: 409,
    ApiErrorCode.SURVEY_INVALID_FIELD: 400,
    ApiErrorCode.PANDA_NOT_FOUND: 404,
    ApiErrorCode.PANDA_NOT_OWNER: 403,
    ApiErrorCode.PANDA_MINT_DISABLED: 403,
    ApiErrorCode.PANDA_MAX_SUPPLY: 403,
    ApiErrorCode.PANDA_MINT_RATE_LIMIT: 429,
    ApiErrorCode.PANDA_TX_FAILED: 500,
    ApiErrorCode.PANDA_NAME_INVALID: 400,
    ApiErrorCode.PANDA_NAME_PROFANITY: 400,
    ApiErrorCode.PANDA_IS_TRADING: 409,
    ApiErrorCode.STRATEGY_TEXT_TOO_SHORT: 400,
    ApiErrorCode.STRATEGY_TEXT_TOO_LONG: 400,
    ApiErrorCode.STRATEGY_BODY_EMPTY: 400,
    ApiErrorCode.STRATEGY_NO_VALID_RULES: 422,
    ApiErrorCode.STRATEGY_RULE_INVALID: 422,
    ApiErrorCode.STRATEGY_PARSE_FAILED: 422,
    ApiErrorCode.STRATEGY_RATE_LIMIT: 429,
    ApiErrorCode.STRATEGY_NOT_FOUND: 404,
    ApiErrorCode.STRATEGY_POLICY_CONFLICT: 422,
    ApiErrorCode.SIM_ALREADY_RUNNING: 409,
    ApiErrorCode.SIM_NO_STRATEGY: 400,
    ApiErrorCode.SIM_INVALID_SPEED: 400,
    ApiErrorCode.SIM_NOT_RUNNING: 400,
    ApiErrorCode.VAULT_NOT_FOUND: 404,
    ApiErrorCode.VAULT_NOT_ACTIVE: 409,
    ApiErrorCode.VAULT_OWNER_MISMATCH: 403,
    ApiErrorCode.VAULT_SYNC_PENDING: 409,
    ApiErrorCode.POLICY_NOT_FOUND: 404,
    ApiErrorCode.POLICY_PAUSED: 409,
    ApiErrorCode.POLICY_PAIR_NOT_ALLOWED: 422,
    ApiErrorCode.POLICY_NOTIONAL_EXCEEDED: 422,
    ApiErrorCode.POLICY_DAILY_LOSS_EXCEEDED: 422,
    ApiErrorCode.POLICY_VERSION_STALE: 409,
    ApiErrorCode.POLICY_AGENT_REVOKED: 409,
    ApiErrorCode.POLICY_MIRROR_STALE: 409,
    ApiErrorCode.LEDGER_ACCOUNT_NOT_FOUND: 404,
    ApiErrorCode.LEDGER_INSUFFICIENT_BALANCE: 409,
    ApiErrorCode.LEDGER_POSITION_NOT_FOUND: 404,
    ApiErrorCode.LEDGER_TRANSACTION_FAILED: 500,
    ApiErrorCode.TRADE_FACT_NOT_FOUND: 404,
    ApiErrorCode.TRADE_FACT_ALREADY_REVIEWED: 409,
    ApiErrorCode.TRADE_FACT_PROOF_NOT_ELIGIBLE: 422,
    ApiErrorCode.CHAIN_PROOF_DISABLED: 403,
    ApiErrorCode.CHAIN_PROOF_DUPLICATE: 409,
    ApiErrorCode.CHAIN_PROOF_RATE_LIMITED: 429,
    ApiErrorCode.CHAIN_PROOF_TX_FAILED: 500,
    ApiErrorCode.AGENT_SIGNER_NOT_CONFIGURED: 503,
    ApiErrorCode.AGENT_SIGNER_UNAUTHORIZED: 403,
    ApiErrorCode.AGENT_SIGNER_NETWORK_NOT_ALLOWED: 403,
    ApiErrorCode.REVIEW_NOT_FOUND: 404,
    ApiErrorCode.REVIEW_NOT_READY: 409,
    ApiErrorCode.REVIEW_EVIDENCE_MISSING: 422,
    ApiErrorCode.SKILL_VERSION_NOT_FOUND: 404,
}


class ApiError(Exception):
    """Raised by services; mapped to { success: false, error: {...} } by handler."""

    def __init__(
        self,
        code: ApiErrorCode,
        message: str,
        *,
        details: Any | None = None,
        invalid_rules: list[dict[str, Any]] | None = None,
        policy_conflicts: list[dict[str, Any]] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details
        self.invalid_rules = invalid_rules
        self.policy_conflicts = policy_conflicts

    @property
    def status_code(self) -> int:
        return HTTP_STATUS_BY_CODE.get(self.code, 500)

    def to_body(self) -> dict[str, Any]:
        body: dict[str, Any] = {
            "code": self.code.value,
            "message": self.message,
        }
        if self.details is not None:
            body["details"] = self.details
        if self.invalid_rules is not None:
            body["invalid_rules"] = self.invalid_rules
        if self.policy_conflicts is not None:
            body["policy_conflicts"] = self.policy_conflicts
        return body
